/* Generated by MBASIC-2025 compiler */
/* Target: CP/M via z88dk */

/* Memory configuration */
#pragma output REGISTER_SP = 0xFC00
#pragma output CRT_STACK_SIZE = 1024
#pragma output CLIB_MALLOC_HEAP_SIZE = 4096

#define MB25_NUM_STRINGS 5
#define MB25_POOL_SIZE 2048  /* String pool size */
#include "mb25_string.h"

#define STR__TEMP_BASE 0

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdint.h>

int main() {
    /* Initialize string system */
    if (mb25_init(MB25_POOL_SIZE) != MB25_SUCCESS) {
        fprintf(stderr, "?Out of memory\n");
        return 1;
    }

    float f, s;
    char input_buffer[256];  /* For INPUT statements */

    /* GOSUB return stack */
    int gosub_stack[100];  /* Return IDs (0, 1, 2...) - not line numbers */
    int gosub_sp = 0;      /* Stack pointer */

line_10:
    /* Test with custom memory settings */
line_20:
    {
        mb25_string_alloc_const(0, "Memory test");
        char *temp_str = mb25_to_c_string(0);
        if (temp_str) {
            printf("%s\n", temp_str);
            free(temp_str);
        }
    }
line_30:
    f = ((0), 16384)  /* FRE(n) - free memory (simulated) */;
line_40:
    s = (mb25_garbage_collect(), mb25_get_free_space());
line_50:
    {
        mb25_string_alloc_const(2, "Total:");
        char *temp_str = mb25_to_c_string(2);
        if (temp_str) {
            printf("%s", temp_str);
            free(temp_str);
        }
    }
    printf("%g", f);
    {
        mb25_string_alloc_const(3, "String pool:");
        char *temp_str = mb25_to_c_string(3);
        if (temp_str) {
            printf("%s", temp_str);
            free(temp_str);
        }
    }
    printf("%g\n", s);
line_60:
    goto program_end;

program_end:
    mb25_cleanup();
    return 0;
}
