/* Generated by MBASIC-2025 compiler */
/* Target: CP/M via z88dk */

/* Memory configuration */
/* Stack pointer auto-detected by z88dk from BDOS (address 0x0006) */
#pragma output CRT_STACK_SIZE = 512
#pragma output CLIB_MALLOC_HEAP_SIZE = 5120

#define MB25_NUM_STRINGS 5
#define MB25_POOL_SIZE 2048  /* String pool size */
#include "mb25_string.h"

#define STR__TEMP_BASE 0

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdint.h>

int main() {
    /* Initialize string system */
    if (mb25_init(MB25_POOL_SIZE) != MB25_SUCCESS) {
        fprintf(stderr, "?Out of memory\n");
        return 1;
    }

    float f;
    char input_buffer[256];  /* For INPUT statements */

    /* GOSUB return stack */
    int gosub_stack[100];  /* Return IDs (0, 1, 2...) - not line numbers */
    int gosub_sp = 0;      /* Stack pointer */

line_10:
    /* Test FRE function */
line_20:
    {
        mb25_string_alloc_const(0, "Testing FRE() function");
        char *temp_str = mb25_to_c_string(0);
        if (temp_str) {
            printf("%s\n", temp_str);
            free(temp_str);
        }
    }
line_30:
    f = ((0), 16384)  /* FRE(n) - free memory (simulated) */;
line_40:
    {
        mb25_string_alloc_const(1, "Free memory:");
        char *temp_str = mb25_to_c_string(1);
        if (temp_str) {
            printf("%s", temp_str);
            free(temp_str);
        }
    }
    printf("%g", f);
    {
        mb25_string_alloc_const(2, "bytes");
        char *temp_str = mb25_to_c_string(2);
        if (temp_str) {
            printf("%s\n", temp_str);
            free(temp_str);
        }
    }
line_50:
    if ((f > 0)) {
        {
            mb25_string_alloc_const(3, "Memory available");
            char *temp_str = mb25_to_c_string(3);
            if (temp_str) {
                printf("%s\n", temp_str);
                free(temp_str);
            }
        }
    }
line_60:
    goto program_end;

program_end:
    mb25_cleanup();
    return 0;
}
