/* Generated by MBASIC-2025 compiler */
/* Target: CP/M via z88dk */

/* Memory configuration */
/* Stack pointer auto-detected by z88dk from BDOS (address 0x0006) */
/* Heap size auto-detected at runtime using -DAMALLOC (75% of TPA) */
#pragma output CRT_STACK_SIZE = 512

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdint.h>

int main() {
    float a, b, c;

    /* GOSUB return stack */
    int gosub_stack[100];  /* Return IDs (0, 1, 2...) - not line numbers */
    int gosub_sp = 0;      /* Stack pointer */

line_10:
    /* Test all remaining compiler features */
line_20:
    /* File operations */
line_30:
    /* RESET - no files to close */
line_40:
    {
        char _old_name[256];
        char _new_name[256];
        mb25_get_string_data(0  /* string in numeric context */, _old_name, sizeof(_old_name));
        mb25_get_string_data(0  /* string in numeric context */, _new_name, sizeof(_new_name));
        if (rename(_old_name, _new_name) != 0) {
            fprintf(stderr, "?File not found\n");
        }
    }
line_50:
    /* FILES statement not implemented - requires CP/M BDOS calls */
    /* Would list files matching: 0  /* string in numeric context */ */
line_60:
    /* Display operations */
line_70:
    /* WIDTH 80 - not implemented (display feature) */
line_80:
    mb25_print_string(0  /* string in numeric context */);
line_90:
    /* Memory and system */
line_100:
    /* CLEAR - close all files (variable clearing not supported in compiled code) */
line_110:
    a = (float)((long)&b);
line_120:
    c = ((float (*)(void))(int)(16384))();
line_130:
    /* CALL machine language routine at address */
    ((void (*)(void))(int)(16384))();
line_140:
    /* Interpreter-only features (should warn) */
line_150:
    /* CHAIN statement not implemented - interpreter-only feature */
    /* Would chain to: 0  /* string in numeric context */ */
line_160:
    /* COMMON x, y, z - used with CHAIN (not supported) */
line_170:
    return 0;

program_end:
    return 0;
}
