/* Generated by MBASIC-2025 compiler */
/* Target: CP/M via z88dk */

/* Memory configuration */
/* Stack pointer auto-detected by z88dk from BDOS (address 0x0006) */
/* Heap size auto-detected at runtime using -DAMALLOC (75% of TPA) */
#pragma output CRT_STACK_SIZE = 512

#define MB25_NUM_STRINGS 4
#include "mb25_string.h"

#define STR__TEMP_BASE 0

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdint.h>

int main() {
    /* Initialize string system */
    /* With -DAMALLOC, heap is ~75% of TPA. Use fixed pool that fits comfortably. */
    if (mb25_init(2048) != MB25_SUCCESS) {
        fprintf(stderr, "?Out of memory\n");
        return 1;
    }

    float a, b;
    char input_buffer[256];  /* For INPUT statements */

    /* GOSUB return stack */
    int gosub_stack[100];  /* Return IDs (0, 1, 2...) - not line numbers */
    int gosub_sp = 0;      /* Stack pointer */

line_10:
    /* Test VARPTR function */
line_20:
    a = 10;
line_30:
    b = (float)((long)&a);
line_40:
    mb25_string_alloc_const(0, "Address of A:");
    mb25_print_string(0);
    printf("%g\n", b);
line_50:
    goto program_end;

program_end:
    mb25_cleanup();
    return 0;
}
