#!/usr/bin/env node
// Generated by MBASIC-2025 JavaScript Backend
// Source: test_hello.bas

(function() {
  'use strict';

  // ===== Runtime Library =====
  function _error(msg) {
    throw new Error("?" + msg);
  }

  function _print(str, newline = true) {
    const s = String(str);
    if (typeof window !== "undefined") {
      // Browser
      const output = document.getElementById("output");
      if (output) {
        output.textContent += s;
        if (newline) output.textContent += "\n";
      }
    } else if (typeof process !== "undefined") {
      // Node.js
      if (newline) {
        console.log(s);
      } else {
        process.stdout.write(s);
      }
    }
  }

  // Math functions
  const _abs = Math.abs;
  const _int = Math.floor;
  const _sqr = Math.sqrt;
  const _sin = Math.sin;
  const _cos = Math.cos;
  const _tan = Math.tan;
  const _atn = Math.atan;
  const _log = Math.log;
  const _exp = Math.exp;

  // String functions
  function _left(str, n) { return String(str).substring(0, n); }
  function _right(str, n) { const s = String(str); return s.substring(s.length - n); }
  function _mid(str, start, len) {
    const s = String(str);
    if (len === undefined) return s.substring(start - 1);
    return s.substring(start - 1, start - 1 + len);
  }
  function _len(str) { return String(str).length; }
  function _chr(n) { return String.fromCharCode(n); }
  function _asc(str) { return String(str).charCodeAt(0) || 0; }
  function _str(n) { return " " + n; }
  function _val(str) { return parseFloat(String(str).trim()) || 0; }

  // FOR/NEXT loop state
  const _for_loops = {};  // Map var name -> {end, step, line}


  // ===== Variables =====
  let i = 0;

  // ===== Program =====
  function main() {
    let _pc = 10;

    while (_pc !== null) {
      switch (_pc) {
        case 10:
          _pc = 20;
          break;
        case 20:
          _print("HELLO, WORLD!", false);
          _pc = 30;
          break;
        case 30:
          {
            const _end = 5.0;
            const _step = 1;
            i = 1.0;
            const _start_ok = (_step > 0) ? (i <= _end) : (i >= _end);
            if (_start_ok) {
              _for_loops["i"] = {
                end: _end,
                step: _step,
                line: 40
              };
            } else {
              // Skip loop - condition not met
              // TODO: Jump to line after NEXT
            }
          }
          _pc = 40;
          break;
        case 40:
          _print("COUNT: ", false);
          _print(i, false);
          _pc = 50;
          break;
        case 50:
          if (_for_loops["i"]) {
            const _loop = _for_loops["i"];
            i += _loop.step;
            const _continue = (_loop.step > 0) ? (i <= _loop.end) : (i >= _loop.end);
            if (_continue) {
              _pc = _loop.line;
              break;
            } else {
              delete _for_loops["i"];
            }
          }
          _pc = 60;
          break;
        case 60:
          _print("DONE", false);
          _pc = 70;
          break;
        case 70:
          _pc = null;
          return;
        default:
          _error(`Undefined line number ${_pc}`);
          return;
      }
    }
  }

  // ===== Execute =====
  try {
    main();
  } catch (e) {
    _print(e.message);
    if (typeof process !== "undefined") process.exit(1);
  }
})();
