/* Generated by MBASIC-2025 compiler */
/* Target: CP/M via z88dk */

/* Define heap for malloc */
#pragma output REGISTER_SP = 0xF000
#pragma output CRT_STACK_SIZE = 512
#pragma output CLIB_MALLOC_HEAP_SIZE = 2048

#define MB25_NUM_STRINGS 8
#define MB25_POOL_SIZE 1024  /* 1KB string pool */
#include "mb25_string.h"

#define STR_A 0
#define STR_B 1
#define STR_C 2
#define STR__TEMP_BASE 3

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdint.h>

int main() {
    /* Initialize string system */
    if (mb25_init(MB25_POOL_SIZE) != MB25_SUCCESS) {
        fprintf(stderr, "?Out of memory\n");
        return 1;
    }

    float f, s, s2, x, f2;
    char input_buffer[256];  /* For INPUT statements */

    /* GOSUB return stack */
    int gosub_stack[100];  /* Return IDs (0, 1, 2...) - not line numbers */
    int gosub_sp = 0;      /* Stack pointer */

line_10:
    /* Test FRE() function - both numeric and string forms */
line_20:
    {
        mb25_string_alloc_const(3, "Testing FRE() function");
        char *temp_str = mb25_to_c_string(3);
        if (temp_str) {
            printf("%s\n", temp_str);
            free(temp_str);
        }
    }
line_30:
    printf("\n");
line_40:
    /* Test FRE(0) - total free memory */
line_50:
    f = ((0), 16384)  /* FRE(n) - free memory (simulated) */;
line_60:
    {
        mb25_string_alloc_const(4, "FRE(0) - Total free memory:");
        char *temp_str = mb25_to_c_string(4);
        if (temp_str) {
            printf("%s", temp_str);
            free(temp_str);
        }
    }
    printf("%g", f);
    {
        mb25_string_alloc_const(5, "bytes");
        char *temp_str = mb25_to_c_string(5);
        if (temp_str) {
            printf("%s\n", temp_str);
            free(temp_str);
        }
    }
line_70:
    printf("\n");
line_80:
    /* Test FRE("") - string pool free space */
line_90:
    s = (mb25_garbage_collect(), mb25_get_free_space());
line_100:
    {
        char *temp_str = mb25_to_c_string(0  /* unsupported string expression */);
        if (temp_str) {
            printf("%s", temp_str);
            free(temp_str);
        }
    }
    printf("%g", s);
    {
        mb25_string_alloc_const(7, "bytes");
        char *temp_str = mb25_to_c_string(7);
        if (temp_str) {
            printf("%s\n", temp_str);
            free(temp_str);
        }
    }
line_110:
    printf("\n");
line_120:
    /* Allocate some strings */
line_130:
    mb25_string_alloc_const(STR_A, "Hello, World!");
line_140:
    mb25_string_alloc_const(STR_B, "This is a test string.");
line_150:
    mb25_string_alloc_const(STR_C, "More string data here.");
line_160:
    {
        mb25_string_alloc_const(3, "Allocated 3 strings:");
        char *temp_str = mb25_to_c_string(3);
        if (temp_str) {
            printf("%s\n", temp_str);
            free(temp_str);
        }
    }
line_170:
    {
        mb25_string_alloc_const(4, "  A$ = ");
        char *temp_str = mb25_to_c_string(4);
        if (temp_str) {
            printf("%s", temp_str);
            free(temp_str);
        }
    }
    {
        char *temp_str = mb25_to_c_string(STR_A);
        if (temp_str) {
            printf("%s\n", temp_str);
            free(temp_str);
        }
    }
line_180:
    {
        mb25_string_alloc_const(5, "  B$ = ");
        char *temp_str = mb25_to_c_string(5);
        if (temp_str) {
            printf("%s", temp_str);
            free(temp_str);
        }
    }
    {
        char *temp_str = mb25_to_c_string(STR_B);
        if (temp_str) {
            printf("%s\n", temp_str);
            free(temp_str);
        }
    }
line_190:
    {
        mb25_string_alloc_const(6, "  C$ = ");
        char *temp_str = mb25_to_c_string(6);
        if (temp_str) {
            printf("%s", temp_str);
            free(temp_str);
        }
    }
    {
        char *temp_str = mb25_to_c_string(STR_C);
        if (temp_str) {
            printf("%s\n", temp_str);
            free(temp_str);
        }
    }
line_200:
    printf("\n");
line_210:
    /* Check string pool free space after allocation */
line_220:
    s2 = (mb25_garbage_collect(), mb25_get_free_space());
line_230:
    {
        char *temp_str = mb25_to_c_string(0  /* unsupported string expression */);
        if (temp_str) {
            printf("%s", temp_str);
            free(temp_str);
        }
    }
    printf("%g", s2);
    {
        mb25_string_alloc_const(3, "bytes");
        char *temp_str = mb25_to_c_string(3);
        if (temp_str) {
            printf("%s\n", temp_str);
            free(temp_str);
        }
    }
line_240:
    {
        mb25_string_alloc_const(4, "String space used:");
        char *temp_str = mb25_to_c_string(4);
        if (temp_str) {
            printf("%s", temp_str);
            free(temp_str);
        }
    }
    printf("%g", (s - s2));
    {
        mb25_string_alloc_const(5, "bytes");
        char *temp_str = mb25_to_c_string(5);
        if (temp_str) {
            printf("%s\n", temp_str);
            free(temp_str);
        }
    }
line_250:
    printf("\n");
line_260:
    /* Test FRE(numeric expression) */
line_270:
    x = 5;
line_280:
    f2 = (((x + x)), 16384)  /* FRE(n) - free memory (simulated) */;
line_290:
    {
        mb25_string_alloc_const(6, "FRE(X*2) where X=5:");
        char *temp_str = mb25_to_c_string(6);
        if (temp_str) {
            printf("%s", temp_str);
            free(temp_str);
        }
    }
    printf("%g", f2);
    {
        mb25_string_alloc_const(7, "bytes");
        char *temp_str = mb25_to_c_string(7);
        if (temp_str) {
            printf("%s\n", temp_str);
            free(temp_str);
        }
    }
line_300:
    goto program_end;

program_end:
    mb25_cleanup();
    return 0;
}
